export interface InvestorGuideFaqItem {
  question: string;
  answer: string;
}

export type GuideIconId = 'building' | 'handshake' | 'balance' | 'search' | 'document' | 'calendar';

export interface InvestorGuide {
  slug: string;
  title: string;
  excerpt: string;
  /** Optional cover subtitle under the white-paper title (falls back to excerpt). */
  subtitle?: string;
  /** Document code on the booklet cover footer, e.g. "KP/WP-2026-07-CG". */
  docCode?: string;
  readTime: string;
  /** Publication date shown in the article byline, e.g. "June 1, 2026". */
  date: string;
  /** ISO-style date for the booklet cover, e.g. "2026-07-30". */
  coverDate?: string;
  content: string;
  icon: GuideIconId;
  /** Three to four scannable takeaways shown before the full text. */
  takeaways: string[];
  /** Source-cited data points shown as the key-findings bullet list after the intro. Falls back to takeaways. */
  stats?: string[];
  faq?: InvestorGuideFaqItem[];
  /**
   * When true, the handcrafted PDF under /public/downloads/guides/{slug}.pdf is used as-is
   * and `npm run pdfs` will not overwrite it. On-page reading embeds that PDF in the booklet frame.
   */
  customPdf?: boolean;
  /** Page count for the custom PDF booklet pager. */
  pdfPageCount?: number;
}

/** Generated by `npm run pdfs` into /public/downloads/guides. */
export function investorGuidePdfUrl(slug: string): string {
  return `/downloads/guides/${slug}.pdf`;
}

export const investorGuides: InvestorGuide[] = [
  {
    slug: 'the-confidence-gap-middle-market-ma-q2-2026',
    title: 'The Confidence Gap: What the Q2 2026 Reversal Reveals About Middle-Market M&A',
    excerpt:
      'Why deal value collapsed even as deal count and sentiment held firm, why the valuation gap now has a second axis, and what it takes to close cleanly in the second half of 2026.',
    subtitle:
      'Why Deal Value Collapsed While Sentiment Held, and How to Close Cleanly in H2 2026',
    docCode: 'KP/WP-2026-07-CG',
    readTime: '16 min read',
    date: 'July 30, 2026',
    coverDate: '2026-07-30',
    icon: 'document',
    customPdf: true,
    pdfPageCount: 13,
    takeaways: [
      'US PE deal value fell to $177.3B in Q2 2026 while deal count held flat — sponsors kept transacting at smaller average sizes.',
      'The valuation gap now runs on two axes: growth and rates, plus AI-driven disruption risk to the revenue base.',
      'Capital is not short; 54.4% of global dry powder sits in the two-to-five-year vintage bucket, an all-time high.',
      'Lower middle market pricing is more conservative than upper-middle headlines; financing terms are no longer a one-way tailwind.',
    ],
    stats: [
      'US private equity deal value fell to $177.3 billion in Q2 2026, down 37.5% quarter-over-quarter and 23.9% year-over-year, while deal count held essentially flat and was up 11.5% year-over-year (Source: PitchBook, Q2 2026 US PE Breakdown).',
      'Year-to-date deal value through Q2 totaled $461 billion, down 10.6% from H1 2025 and well below the $647.8 billion posted in H2 2025 (Source: PitchBook, Q2 2026 US PE Breakdown).',
      '54.4% of global private capital dry powder sat in the two-to-five-year vintage bucket as of Q1 2025, an all-time high versus prior post-shock peaks of 45% and 52.7% (Source: PitchBook, Q3 2025 Global Private Market Fundraising Report).',
      'US middle-market PE funds alone held $595.2 billion in dry powder as of mid-2025, representing 53.1% of total US PE dry powder (Source: PitchBook, 2025 Annual US PE Middle Market Report).',
      'Median entry TEV/EBITDA closed 2025 at 13.4x for $500M–$1B deals versus 8.8x for $25M–$100M deals, a 4.6-turn spread up from roughly 3.4 turns in 2023 (Source: PitchBook, Q1 2026 US PE Middle Market Report).',
      'Direct-lending spreads on sponsor-backed LBOs widened roughly 25 to 50 basis points, with a recent sample averaging S+509 versus S+474 in Q1 2026 (Source: PitchBook | LCD, via Q2 2026 US PE Breakdown).',
    ],
    content: `Middle-market M&A entered 2026 on the strongest sentiment readings in six years. It is exiting the first half on its weakest quarterly print since late 2023. US private equity deal value fell to $177.3 billion in Q2 2026, down 37.5% quarter-over-quarter and 23.9% year-over-year, even as deal count held essentially flat and was up 11.5% year-over-year. Confidence and price discovery diverged, and the gap between them is the real story of H1 2026.

The proximate causes are identifiable: conflict in Iran, an energy-price spike, and a return of inflation concerns pushed dealmakers toward caution and widened the gap between buyer and seller rate assumptions. But a second, more durable driver is emerging underneath the macro shock. When PitchBook's Q2 2026 survey asked private equity respondents what most often separates what buyers will pay from what sellers will accept, the top answer was differing assumptions about revenue growth. What is new is the second-most-cited factor: disagreement over whether a target's revenue base can withstand AI-driven disruption.

At the same time, capital is not the constraint. Private equity dry powder remains near record levels, and the share of global dry powder aged two to five years reached an all-time high of 54.4%, meaning a larger share of committed capital is under deployment pressure now than at any comparable point after the dot-com bust or the financial crisis. The middle market itself is bifurcating: multiples and leverage are both expanding at the upper end of the size spectrum while the lower middle market lags, and the financing market that fueled 2024's rebound has partially reversed.

This paper works through what actually happened in Q2 2026, why the valuation gap now runs on two axes instead of one, where the aging capital overhang is likely to push deal activity in H2, and what that implies for how a sale, raise, or acquisition should be built and financed through year-end.

## The Setup: Two Data Sets, One Contradiction

Two credible data sets describe the 2026 middle market, and they do not agree. The first is sentiment: multiple bank and advisory surveys published in the first half of 2026 reported the strongest dealmaker confidence readings in roughly six years. That reading is genuine and reflects real tailwinds: normalizing rate expectations earlier in the year, record private capital dry powder, and pent-up sponsor pressure to exit aging holdings.

The second data set is the actual transaction record. US private equity deal value collapsed in Q2 2026 to its lowest level since Q4 2023, even as transaction flow held firm: 2,384 announced and estimated deals, flat quarter-over-quarter and up 11.5% year-over-year, against aggregate value of $177.3 billion. The combination of a steady deal count and collapsing deal value means sponsors kept transacting through Q2, just at dramatically smaller average deal sizes, retreating from the large, financing-dependent transactions that had powered the prior two quarters.

## The Data: What Actually Happened in Q2 2026

The proximate trigger was macro, not structural. Conflict in Iran, a spike in energy prices, and renewed inflation concerns hit in the second quarter and pushed dealmakers toward caution. The immediate effect showed up first in financing: the gap in rate assumptions between buyers and sellers widened from Q1, and sponsors pulled back most sharply from the large, leverage-dependent transactions that require committed financing weeks or months in advance. Smaller, less financing-sensitive deals continued to close at a steady pace, which is why deal count barely moved while deal value fell by more than a third in a single quarter.

## The New Axis of the Valuation Gap

Every account of the 2023-2024 M&A slowdown centered on one story: sellers anchored to 2021-era multiples, buyers underwriting to a higher cost of capital, and a bid-ask spread wide enough to stall processes. That story is still true in 2026, but it is no longer the whole story.

PitchBook's Q2 2026 US PE survey asked respondents what most often separates what buyers will pay from what sellers will accept. The most common answer remains differing assumptions about future revenue growth. But for the first time, a second, distinct factor now registers separately: disagreement over a target's ability to defend its revenue base against AI-driven disruption. The valuation gap is no longer only a function of rates and multiples. It is increasingly a disagreement about whether a company's revenue base can survive the disruption from AI.

A seller who can address the AI-disruption question directly, with a specific, evidenced view of how the business's revenue, margin, or customer relationships hold up against AI-native competitors or AI-enabled substitution, is negotiating from a fundamentally different position than one who leaves the buyer to assume the worst. In software, services, and anything with a labor-cost-arbitrage business model, that question is now doing as much work in price discovery as the interest rate line in a buyer's model.

## Capital Is Not Short, Just Aging

None of the above reflects a shortage of capital. Private equity dry powder remains near record levels globally, and in the US, middle-market PE funds alone held $595.2 billion in dry powder as of mid-2025. What has changed is the age profile of that capital. As of Q1 2025, 54.4% of global private capital dry powder sat in the two-to-five-year vintage bucket, an all-time high exceeding prior cycle peaks after the dot-com bust and the global financial crisis.

Fund managers sitting on 2020-2023 vintage commitments face a genuine clock: standard investment periods do not extend indefinitely. That pressure does not show up as looser underwriting on its own (Q2's reversal shows sponsors are still willing to walk away from large deals when financing or valuation terms do not clear), but it does mean the incentive to find deployable deals will intensify through H2 2026 and into 2027.

## The Middle Market Is Bifurcating

Aggregate middle-market valuation multiples understate what is happening beneath the surface. Decomposing the headline multiple by deal size shows firmness in 2025 valuations concentrated almost entirely at the larger end. Median entry TEV/EBITDA for deals between $500 million and $1 billion closed 2025 at 13.4x, against 8.8x for deals between $25 million and $100 million, a spread of roughly 4.6 turns, up from about 3.4 turns in 2023. Leverage has scaled in parallel: median net debt/EBITDA reached 5.2x for the largest band versus 2.5x for the smallest.

Competition is concentrating at the upper end of the middle market, while the lower middle market prices more conservatively and carries less debt. The more likely path for further multiple expansion in H2 2026 is in the lower middle market, not the upper end, a dynamic worth underwriting to directly rather than assuming a single middle-market multiple applies uniformly.

## The Financing Whiplash

After several years in which direct lenders steadily took share from the broadly syndicated loan market for sponsor-backed LBO financing, the BSL market reclaimed the majority of LBO financing volume in 2026. Direct lending spreads widened roughly 25 to 50 basis points on plain-vanilla deals, with a small sample of recent LBOs pricing at an average of S+509, up from S+474 in Q1 2026. This is the first spread-widening move direct lending has seen in several quarters.

The whiplash is concentrated in the upper-middle-market, sponsor-backed LBO segment where direct lending and BSL compete directly, precisely the segment where Q2's deal-value collapse was sharpest. Spreads in the traditional middle-market segment (borrowers with EBITDA below $100 million) have stabilized in a 450-to-525-basis-point range with all-in yields near 9%.

## Implications by Seat

For owners preparing to sell or raise capital, two distinct questions now need direct answers before a process launches: the traditional valuation-growth question, and the newer AI-disruption-resilience question. Owners in the lower middle market should recognize that the pricing environment in their segment is structurally more conservative than upper-middle-market headlines suggest.

For sponsors and buyers, the aging dry powder overhang creates real pressure to deploy, but Q2's reversal shows the market is not simply chasing deals. The more durable opportunity may be in the lower middle market, where multiple expansion has more room to run and where deals are less exposed to the financing whiplash at the top of the range.

For both sides, financing terms are no longer a one-way tailwind. Processes built around a credible, less leverage-dependent capital structure are more likely to survive a financing market that is still finding its footing after Q2.

## Risk Considerations and Counterargument

Three risks deserve direct treatment. First, the Q2 2026 reversal could reflect a temporary macro shock rather than a durable shift; if the Iran conflict and energy-price spike fade, H2 deal value could recover quickly. Second, the aging-dry-powder overhang has historically required a genuinely more robust deal market to work down, not gradual absorption. Third, the financing whiplash between direct lending and BSL is based on a relatively thin, recent sample; treat basis-point figures as directionally indicative.

These risks argue for building in optionality on financing structure, timing, and how a valuation narrative addresses AI-disruption risk, rather than for standing down from the market.

## Forward Look: 12-Month Outlook

The H2 2026 to H1 2027 window is likely to be shaped by three forces: a partial recovery in deal value as the macro shock fades, continued deployment pressure from aging dry powder supporting deal count, and structural persistence of both the financing reset and the AI-disruption axis of the valuation gap through at least mid-2027.

Our outlook: deal count in the middle market holds up better than deal value through H2 2026, with more durable multiple expansion concentrated in the lower middle market. Owners and sponsors who build a specific, evidenced answer to the AI-disruption question into their process materials should see meaningfully shorter timelines and fewer post-LOI re-trades than those who do not.

## Conclusion

The headline story of H1 2026, the strongest middle-market sentiment in six years, is real but incomplete. Underneath it, Q2 delivered the sharpest quarterly reversal in deal value since late 2023, revealing a valuation gap that now runs on two axes. Capital is not the constraint; discipline and preparation are. The businesses, sponsors, and lenders who treat 2026 as a market that rewards specific, evidenced answers over general optimism are the ones positioned to transact well through year-end.`,
    faq: [
      {
        question: 'Did middle-market M&A actually slow down in 2026?',
        answer:
          'Deal value did, sharply, in Q2 2026: down 37.5% quarter-over-quarter and 23.9% year-over-year to $177.3 billion, the lowest quarterly print since Q4 2023. Deal count did not: 2,384 announced and estimated transactions, roughly flat quarter-over-quarter and up 11.5% year-over-year. Sponsors kept transacting; they retreated from large, financing-dependent deals toward smaller average sizes. Reading “slowdown” from value alone misses that distinction (PitchBook, Q2 2026 US PE Breakdown).',
      },
      {
        question: 'What is the “confidence gap” this paper describes?',
        answer:
          'It is the divergence between dealmaker sentiment and realized transaction outcomes in H1 2026. Multiple bank and advisory surveys reported the strongest middle-market confidence readings in roughly six years, while Q2 delivered the weakest PE deal-value print since late 2023. Confidence and price discovery pulled apart: optimism about dry powder and rates did not translate into large, leverage-heavy closes when financing assumptions and valuation narratives failed to clear.',
      },
      {
        question: 'What is actually driving the valuation gap between buyers and sellers in 2026?',
        answer:
          'Differing assumptions about revenue growth remain the most commonly cited driver. A newer, second factor now registers separately in PitchBook’s Q2 2026 US PE survey: disagreement over whether a target’s revenue base can withstand AI-driven disruption. The gap is no longer only rates and multiples. In software, services, and labor-arbitrage models especially, an evidenced answer to the AI-resilience question can matter as much as the interest-rate line in a buyer’s model.',
      },
      {
        question: 'Is there a shortage of capital available to do deals?',
        answer:
          'No. Private equity dry powder remains near record levels, and US middle-market PE funds alone held $595.2 billion as of mid-2025 (53.1% of total US PE dry powder). The constraint is not availability but age and underwriting discipline: 54.4% of global private capital dry powder sat in the two-to-five-year vintage bucket as of Q1 2025, an all-time high. That creates deployment pressure without forcing sponsors to clear deals on weak terms, as Q2’s reversal showed (PitchBook).',
      },
      {
        question: 'Are middle-market valuation multiples uniform across the size range?',
        answer:
          'No. Median entry TEV/EBITDA for $500M–$1B deals closed 2025 at 13.4x versus 8.8x for $25M–$100M deals, a 4.6-turn spread up from roughly 3.4 turns in 2023. Leverage bifurcated similarly (5.2x net debt/EBITDA at the large end versus 2.5x at the small end). Treating “the middle market” as one pricing environment risks mis-benchmarking a specific process. Further multiple expansion in H2 is more plausible in the lower middle market than at the top of the range (PitchBook, Q1 2026 US PE Middle Market Report).',
      },
      {
        question: 'What happened to private credit and LBO financing in 2026?',
        answer:
          'After several years of direct lenders taking share from broadly syndicated loans, BSL reclaimed the majority of LBO financing volume in 2026. Direct-lending spreads on sponsor-backed LBOs widened roughly 25 to 50 basis points, with a recent sample averaging S+509 versus S+474 in Q1 2026, the first such reset in several quarters. The whiplash is sharpest in the upper-middle-market segment where direct lending and BSL compete directly. Traditional middle-market borrowers (EBITDA below $100M) have seen more stable pricing in a roughly 450–525 bps spread range with all-in yields near 9% (PitchBook | LCD, via Q2 2026 US PE Breakdown).',
      },
      {
        question: 'How should a seller prepare for an H2 2026 process?',
        answer:
          'Build answers to both axes of the valuation gap before launch: a credible growth and margin bridge, and a specific, evidenced view of AI-disruption resilience where it is relevant to the business model. Benchmark pricing to your size band, not upper-middle headlines. Stress-test financing optionality with less leverage-dependent structures so a credit-market wobble does not force a re-trade. Clean diligence files, customer references, and a realistic timeline still matter as much as the narrative.',
      },
      {
        question: 'Where is the better opportunity for sponsors and buyers right now?',
        answer:
          'Aging dry powder creates real pressure to deploy, but Q2 showed the market will still walk away from large deals when financing or valuation does not clear. The more durable opportunity may sit in the lower middle market, where multiple expansion has more room, leverage is structurally lower, and deals are less exposed to the upper-middle financing whiplash. Competitive tension still clears on scarce, well-prepared assets; it does not clear on optimism alone.',
      },
      {
        question: 'Could Q2 2026 simply reverse in H2 if the macro shock fades?',
        answer:
          'A partial recovery in deal value is plausible if the Iran conflict and energy-price spike fade and rate assumptions reconverge. That is one of three risks the paper treats directly. Even in a rebound scenario, the paper argues the financing reset and the AI-disruption axis of the valuation gap are more structural and likely to persist through at least mid-2027. Build optionality on structure, timing, and narrative rather than assuming a clean snap-back to early-2026 conditions.',
      },
      {
        question: 'What is Keningford’s 12-month outlook for middle-market M&A?',
        answer:
          'Deal count should hold up better than deal value through H2 2026, supported by deployment pressure from aging dry powder. More durable multiple expansion is likely concentrated in the lower middle market. Owners and sponsors who put a specific, evidenced AI-disruption answer into process materials should see shorter timelines and fewer post-LOI re-trades than those who leave buyers to assume the worst. Discipline and preparation, not capital scarcity, remain the binding constraints.',
      },
      {
        question: 'Who is Keningford Partners and how do we start a conversation?',
        answer:
          'Keningford Partners is an independent, principal-led capital advisory and M&A firm advising growth-stage and middle-market companies, alongside institutional investors, on equity, debt, and strategic transactions. If you are preparing a sale, raise, or acquisition in H2 2026, contact the team at info@keningfordpartners.com or through keningfordpartners.com/contact.',
      },
    ],
  },
  {
    slug: 'how-family-offices-evaluate-opportunities',
    title: 'How Family Offices Evaluate Opportunities',
    excerpt:
      'What family offices weigh beyond headline returns: alignment, governance, liquidity, and relationship quality.',
    readTime: '10 min read',
    date: 'February 10, 2026',
    icon: 'building',
    takeaways: [
      'Family offices weigh alignment, governance rights, and liquidity as heavily as return potential.',
      'Concise, institutional-quality materials and direct access to decision-makers move processes forward.',
      'A credible equity story with transparent risk disclosure consistently outperforms polished marketing.',
    ],
    content: `Family offices evaluate opportunities through a lens that differs materially from institutional fund managers. Return potential matters, but so do alignment with the family's values, governance rights, liquidity expectations, and the quality of the relationship with sponsors and management teams. Understanding how that lens works, and how it differs from the fund playbook most founders have been coached against, is the difference between a process that builds momentum and one that stalls politely.

The differences begin with structure. A fund manager answers to limited partners on a defined fund life, which disciplines everything from check size to exit timing. A family office answers to a family, which means the mandate can be broader, the hold period longer, and the decision process both faster and more personal. Capital that is not forced to exit is capital that underwrites differently, and founders who present to a family office as if it were a growth fund routinely answer the wrong questions well.

## Investment Criteria

Most family offices begin with sector and stage fit, then assess the durability of cash flows, downside protection, and the credibility of the capital strategy. Direct investments often receive more scrutiny on management quality and governance than fund commitments, because the family cannot diversify a direct position the way a fund diversifies a portfolio. A single direct investment carries the family's name alongside its capital, and the diligence reflects that weight.

Downside protection deserves particular attention in preparation. Where a growth fund models the distribution of outcomes and accepts that some positions go to zero, many family offices underwrite closer to the way a credit committee does: what is the realistic worst case, what does the business look like in that case, and how does the structure protect the position. Founders who arrive with preference math, covenant thinking, and honest downside scenarios already modeled signal that they understand their counterparty.

Sector affinity also runs deeper than a screening filter. Many family offices concentrate where the family built its operating wealth, and in those sectors they bring pattern recognition that rivals any specialist fund. Pitching a logistics-fortune family office on a supply-chain business means presenting to people who may know the working-capital rhythms of the industry better than the founder does. That depth cuts both ways: credibility compounds quickly, and embellishment is detected just as quickly.

## Process Dynamics

Family offices typically move deliberately. They favor concise, institutional-quality materials, clear use of proceeds, and direct access to decision-makers. A fragmented process with multiple handoffs often signals misalignment before terms are even discussed. The founder who insists on routing every exchange through advisors, or who cannot answer capital-structure questions without a banker present, raises a quiet flag that no deck can lower.

Deliberate does not mean slow, and this is the most common misreading of family office behavior. When conviction forms, a principal-led office can move from first meeting to term sheet faster than any investment committee, because the decision may sit with two or three people who talk to each other daily. The deliberateness sits earlier in the process: the months of relationship-building, the unhurried second and third conversations, the preference for watching a management team operate across quarters rather than across a data room.

Founders should plan for that rhythm rather than fight it. The practical implication is to open family office conversations six to twelve months before capital is needed, share updates in the interim that demonstrate execution against stated plans, and treat every interaction as diligence, because it is. An update that quietly walks back a projection made three months earlier does more damage in a family office process than in a fund process, where personnel and attention turn over faster.

## What Differentiates Winners

The best-received opportunities combine a credible equity story, transparent risk disclosure, and a capital structure that leaves room for strategic optionality. Founders who can articulate unit economics and capital priorities without relying on slides alone consistently outperform in family office processes, because unscripted fluency is read as evidence that the numbers live in the operator rather than in the deck.

Transparency on risk carries unusual weight with this investor class. A family office that has operated businesses through cycles has seen every category of corporate distress, and a founder who names the two or three things that could genuinely impair the business, alongside what is being done about them, builds more conviction than one who presents an unblemished story. Omission reads as either inexperience or evasion, and neither supports a long-hold relationship.

Finally, alignment is examined in both directions. The family is deciding whether the founder is someone they want to be partners with for a decade; the founder should be conducting the same evaluation. Asking about the office's decision process, prior direct investments, behavior in downside scenarios, and expectations around information rights is not impertinence, it is exactly the seriousness the best family offices are looking for across the table.`,
  },
  {
    slug: 'how-lps-select-funds',
    title: 'How LPs Select Funds',
    excerpt:
      'How institutional limited partners underwrite emerging and established managers in a selective deployment environment.',
    readTime: '12 min read',
    date: 'March 3, 2026',
    icon: 'handshake',
    takeaways: [
      'LPs scrutinize track record net of fees, loss ratios, pacing, and team stability before terms.',
      'Warm introductions from trusted advisors carry real weight; cold outreach rarely advances.',
      'Disciplined portfolio strategy and realistic fund size win in competitive fundraises.',
    ],
    content: `Limited partners are deploying more selectively than in prior cycles. Investment committees are spending more time on track record quality, team stability, portfolio construction, and the specificity of the manager's edge. For managers in the market, the practical consequence is that fundraises take longer, diligence goes deeper, and the standard of preparation that cleared the bar three years ago now merely earns a second meeting.

The selectivity is structural, not cyclical. Institutional allocators are managing denominator effects from prior-vintage commitments, slower distributions across their existing portfolios, and internal pressure to consolidate manager relationships rather than expand them. Every new commitment therefore competes not only against other funds in the market but against re-ups with incumbent managers the institution already knows. Understanding that competitive frame changes how a manager should present: the pitch is not merely that the fund is good, but that it earns a place on a roster that is actively shrinking.

## Diligence Priorities

LPs evaluate prior fund performance net of fees, loss ratios, pacing, and the consistency of underwriting through market cycles. Gross returns open the conversation; net returns, and the dispersion behind them, decide it. A track record with two outliers and a long tail of write-downs is read very differently from the same multiple built on consistent underwriting, because the LP is buying the process that produced the returns, not the returns themselves.

Attribution receives forensic attention. Committees want to know which partners sourced and drove each deal, whether those partners remain at the firm, and whether the economics of the new fund keep them there. Team stability has become a first-order diligence item: a spine of departures, or carry concentrated in a founder who no longer leads deals, will surface in reference calls regardless of what the fund materials say.

For emerging managers, the bar is higher on differentiation, anchor investor quality, and operational infrastructure. A first-time fund is asking an institution to underwrite a firm that does not yet exist, so evidence substitutes for history: a deal-by-deal track record with verifiable attribution, an anchor whose diligence other LPs respect, a back office that survives operational due diligence, and a thesis specific enough that the LP can articulate why this manager wins the deals the thesis targets.

## Relationship Capital

Access matters. Warm introductions from trusted advisors, existing managers, or portfolio company CEOs carry weight. Cold outreach without a clear thesis and relevant comparables rarely advances, not because allocators are closed-minded but because the volume of inbound makes filtering by referral quality rational. The introduction is itself a data point: who was willing to spend credibility on this manager.

Relationship capital is built between fundraises, not during them. The managers who close efficiently are typically the ones who treated LP communication as a continuous discipline, sharing deal flow observations, honest portfolio updates, and market perspective in the years when they were not asking for money. An allocator who has watched a manager think in writing for two years commits faster than one meeting the firm for the first time alongside a PPM.

Consultants and gatekeepers deserve deliberate attention in that cadence. For many institutions, the consultant's rating determines whether the internal team can even bring a fund to committee. Managers should understand which consultants cover their strategy, engage them early, and treat their process with the same seriousness as a direct LP relationship, because functionally it is one.

## Structuring Considerations

LPs are increasingly attentive to fee structures, key person provisions, and co-investment rights. The headline two-and-twenty matters less than the details around it: fee step-downs after the investment period, management fee offsets, the recycling provisions that determine how much capital actually reaches deals, and the waterfall mechanics that govern when carry is paid and clawed back. Sophisticated LPs read the LPA before the deck.

Key person and governance terms are negotiated with more energy than economics. Allocators have absorbed the lesson of funds where the named partners left mid-fund, so expect specific key person triggers, meaningful GP commitment sized to the principals' net worth rather than a token percentage, and advisory committee rights with substance. Co-investment has moved from a perk to a core part of many LPs' deployment models, and managers who can articulate a credible, fair co-investment allocation policy hold a real advantage.

Managers who present a disciplined portfolio strategy and realistic fund size relative to opportunity set are better positioned in competitive fundraises. Fund-size discipline is read as a proxy for alignment: a manager who raises to the strategy rather than to demand signals that carry, not fees, is the business model. The most damaging pattern an LP can find is strategy drift that tracks fund growth, larger checks, later stages, and broader sectors that quietly abandon the edge the track record was built on.`,
  },
  {
    slug: 'debt-vs-equity',
    title: 'Debt vs Equity',
    excerpt:
      'A practical framework for founders evaluating financing alternatives without defaulting to equity dilution.',
    readTime: '11 min read',
    date: 'March 24, 2026',
    icon: 'balance',
    takeaways: [
      'Debt fits recurring-revenue businesses funding identifiable ROI; equity fits unproven risk capital.',
      'Covenants, dilution, and the signal each structure sends all belong in the comparison.',
      'Hybrid structures often bridge the gap when neither pure debt nor pure equity fits cleanly.',
    ],
    content: `The debt versus equity decision is rarely binary. Founders should evaluate cost of capital, flexibility, covenant constraints, dilution, and the strategic signal each structure sends to customers, employees, and future investors. Most companies at growth stage will use both instruments across their life, and the real question is sequencing: which capital funds which work, in what order, at what cost.

The framing error to avoid is comparing instruments on headline cost alone. Equity looks free because it has no coupon, and debt looks cheap because the interest rate is visible; both readings are wrong. Equity is the most expensive capital a growing company will ever sell, because its cost is a permanent share of every future dollar of value. Debt's visible rate omits covenant constraints, amortization pressure on cash flow, and the refinancing risk that arrives whether or not the business is ready. The honest comparison prices flexibility and downside behavior, not just the coupon line.

## When Debt Fits

Recurring revenue businesses with predictable cash conversion can often support senior or unitranche debt at attractive terms. Debt works best when proceeds fund identifiable ROI, acquisitions with synergy cases, working capital for contracted growth, or refinancing at better terms. The unifying test is whether the funded activity produces cash flows that service the obligation on a timeline the instrument respects; debt against uncertain payback is equity risk wearing a credit structure.

Lender diligence differs from investor diligence in ways that reward specific preparation. Credit committees underwrite downside durability rather than upside: revenue contracted versus assumed, customer concentration, margin behavior in a stress case, and the quality of monthly financial reporting. A company that produces lender-grade reporting, thirteen-week cash forecasts, covenant headroom models, and clean management accounts, will price materially better than an identical business with investor-grade storytelling and accountant-grade numbers.

Covenants deserve as much negotiating attention as pricing. A cheap facility with tight maintenance covenants can become the most expensive capital on the balance sheet the first quarter the plan slips, because a covenant breach transfers negotiating leverage to the lender at exactly the wrong moment. Model covenant headroom under the downside case, not the base case, and treat any facility that only works if the plan is hit as mispriced regardless of its rate.

## When Equity Fits

Equity remains appropriate when the business needs risk capital for unproven initiatives, balance sheet repair, or market expansion where cash payback is uncertain. These are outcomes with wide distributions, and equity is the only instrument designed to absorb wide distributions. Using it for that purpose is not expensive; it is the instrument working as designed.

The right equity partner can also bring sector expertise and follow-on capacity, and these deserve genuine weight in partner selection. Follow-on capacity in particular functions as insurance: an investor who can and does lead the next round removes an entire financing risk from the company's future. Reference-check that behavior directly with portfolio founders, including at least one whose company underperformed, because follow-on behavior in bad quarters is the term that never appears in the term sheet.

Equity's true cost surfaces in structure more than price. Participating preferences, cumulative dividends, broad anti-dilution, and heavy protective provisions can convert a flattering headline valuation into a punishing exit waterfall. Model founder proceeds under at least three exit scenarios before signing anything; a modestly lower valuation with clean structure routinely outperforms a higher number wrapped in participation and ratchets.

## Hybrid Structures

Preferred equity, convertible instruments, and structured common can bridge gaps between pure debt and pure equity. These instruments exist because real financing problems are rarely pure: a company may be too levered for more debt but unwilling to price equity in a soft market, or need capital certainty now with valuation discovery deferred. The optimal structure depends on growth profile, existing leverage, and investor universe.

Each hybrid carries its own discipline. Structured preferred with PIK features preserves cash but compounds quietly, and founders should model the redemption stack at exit rather than at issuance. Convertibles defer the valuation conversation but stack up: three rounds of notes with different caps and discounts create a conversion event that surprises everyone at the priced round. Revenue-based instruments avoid dilution entirely but claim the same operating cash flow that funds growth, which limits them to businesses with genuine margin headroom.

The sequencing insight that ties the framework together is that instruments should match the maturity of what they fund. Prove the unproven with equity, finance the proven with debt, and use hybrids to bridge timing gaps rather than to avoid hard pricing conversations. Companies that let the risk profile of the funded work choose the instrument, rather than defaulting to whichever capital is easiest to raise that quarter, compound ownership meaningfully over a decade.`,
  },
  {
    slug: 'how-due-diligence-works',
    title: 'How Due Diligence Works',
    excerpt:
      'What institutional investors examine in financial, commercial, and legal diligence, and how to prepare.',
    readTime: '13 min read',
    date: 'April 14, 2026',
    icon: 'search',
    takeaways: [
      'Preparation quality directly affects timeline, re-trade risk, and final terms.',
      'Quality-of-earnings work is standard; expect scrutiny on revenue quality and concentration.',
      'Management credibility in live Q&A matters as much as the data room itself.',
    ],
    content: `Due diligence is the process by which investors validate the investment thesis, identify risks, and build conviction for pricing and structure. Preparation quality directly affects timeline, re-trade risk, and ultimate terms. Companies that treat diligence as an audit to be survived consistently leave value on the table; companies that treat it as the operational proof of their narrative consistently close faster and on the terms they signed.

The economics of preparation are asymmetric and worth stating plainly. Every material issue has two prices: the price of fixing it before launch, and the price of the investor finding it first. A gap surfaced in week two of preparation is a task; the same gap surfaced during exclusivity is a re-trade, because by then the company has lost its alternatives and the buyer knows it. Most valuation erosion in private processes happens not at the term sheet but in the quiet weeks after it, one discovered issue at a time.

## Financial Diligence

Investors examine revenue quality, margin durability, working capital seasonality, customer concentration, and normalized EBITDA bridges. Quality-of-earnings work is standard in middle-market processes, and management should assume every adjustment will be rebuilt independently by the buyer's accountants. The goal of preparation is simple to state: when the investor's rebuild of your numbers is complete, it should match yours.

Revenue quality receives the deepest scrutiny because it anchors every multiple. Expect analysis of contracted versus reorder revenue, cohort behavior by acquisition vintage, churn definitions tested against raw data, and any quarter-end revenue patterns that suggest pull-forward. The EBITDA bridge attracts equal attention: each addback needs documentation, a rationale, and internal consistency, because one indefensible adjustment licenses the buyer's advisors to discount the entire schedule.

Working capital is the sleeper issue that surprises otherwise prepared teams. The peg negotiated at closing is set from the trailing profile, so seasonality, receivable aging, and any customer prepayment dynamics should be analyzed and explained before the buyer does the work. A company that presents its own working capital analysis controls that negotiation; a company that waits inherits the buyer's version of it.

## Commercial Diligence

Market size, competitive positioning, retention metrics, and pricing power receive significant attention, frequently through third-party commercial diligence firms who will interview your customers directly. Management should know what those calls will surface before commissioning-side advisors do: run informal win-loss and reference conversations in advance, and address the recurring criticism in the narrative rather than hoping it stays unspoken.

Management's ability to discuss these topics credibly in Q&A often matters as much as the data room. Partners build conviction in unscripted exchanges, watching whether the CEO can defend the market thesis against a skeptical rebuild, whether the CFO knows which cohorts are weakening and why, and whether the team's answers stay consistent across meetings. Rehearsed fluency with the deck is table stakes; the differentiating signal is fluency without it.

## Legal and Governance

Cap tables, material contracts, IP ownership, litigation, and regulatory exposure are reviewed in parallel with the financial and commercial workstreams. Legal diligence rarely changes price directly, but it is the workstream most capable of destroying a timeline, because legal issues tend to be binary: an unsigned IP assignment from a departed co-founder is not discounted, it is fixed or the deal waits.

The recurring offenders are remarkably consistent across processes: option grants never approved by the board, missing assignment agreements from early contractors who touched core IP, material contracts with unflagged change-of-control clauses, and side letters nobody catalogued. Every one of these is inexpensive to cure months before a process and expensive to cure inside one. A pre-launch legal audit by transaction counsel, not company counsel reviewing its own work, is among the highest-return preparation spends available.

Clean documentation and proactive disclosure reduce friction in final documentation, and disclosure strategy deserves genuine thought. Issues disclosed early, with context and a remediation plan, become priced-in facts; issues discovered late become trust problems that contaminate unrelated workstreams. The disclosure schedule is not the place investors learn about a problem for the first time, it is the place they confirm what management already told them.

## Running the Process

Diligence is also an operational load on a company that still has a business to run, and processes fail from exhaustion as often as from findings. Assign a single internal owner for the data room and Q&A flow, route every investor question through one channel with a forty-eight-hour response standard, and maintain a living FAQ so the tenth investor receives the same answer as the first in the same words. Inconsistent answers across parallel conversations are how careless companies manufacture diligence issues out of nothing.

Finally, protect the operating rhythm. Ring-fence the deal team, keep the wider company on quarterly execution, and remember that the strongest diligence artifact of all is a business that hits its numbers during the process. Nothing re-prices a deal downward faster than a company missing its own forecast in the exact quarter it asked to be underwritten on it.`,
  },
  {
    slug: 'what-makes-a-great-investment-memo',
    title: 'What Makes a Great Investment Memo',
    excerpt:
      'The elements institutional investors expect in a concise, credible investment memorandum.',
    readTime: '11 min read',
    date: 'May 5, 2026',
    icon: 'document',
    takeaways: [
      'Lead with the opportunity in one paragraph: what the company does, why it wins, what capital enables.',
      'Replace adjectives with metrics: retention, payback, cohorts, and capital efficiency.',
      'Pairing each material risk with a mitigant builds credibility; omission signals evasiveness.',
    ],
    content: `A strong investment memo distills a complex business into a clear thesis, supported by evidence and honest risk disclosure. It is not a marketing deck, it is the document that earns a second meeting. The distinction matters because the two artifacts do different work: a deck performs in the room with management present to carry it, while a memo circulates alone, gets forwarded to the skeptical partner who was not in the meeting, and is read on a train with no one there to defend it.

Write for that reader. The forwarded-to partner has seen a thousand of these, allocates minutes rather than hours, and is looking for a reason to stop reading. The memo that survives is the one whose first page makes the thesis falsifiable, whose numbers reconcile with each other on every page, and whose author visibly anticipated the objections rather than hoping they would not come up.

## Structure That Works

Lead with the opportunity in one paragraph: what the company does, why it wins, and what capital will enable. If those three clauses cannot be written plainly, the problem is the thesis, not the prose. Follow with market context, business model, financial profile, use of proceeds, and risks, in that order, because it mirrors the order in which an investment committee actually interrogates an opportunity.

Discipline in each section matters more than length. Market context should size the reachable market from the bottom up, customers, pricing, and penetration, rather than quoting a headline TAM no one believes. The business model section should make the unit economics do the arguing: how the company acquires a customer, what that costs, what the customer is worth, and how those numbers have moved over the last eight quarters. Use of proceeds should tie every dollar to a milestone that changes the company's risk profile, because "eighteen months of runway" is a budget, not a plan.

Length itself is a signal. A memo that cannot make its case in roughly ten pages is usually hiding a weak argument inside a long one, and sophisticated readers know it. Depth belongs in the appendix: full cohort tables, model output, and pipeline detail, referenced from the body so the committed reader can verify and the scanning reader is not obstructed.

## Evidence Over Adjectives

Replace superlatives with metrics: retention, payback, cohort performance, pipeline conversion, and capital efficiency. Investors discount narrative without supporting data, and the discount compounds: one unsupported claim licenses skepticism toward every claim that follows it. "Best-in-class retention" is an adjective; "117 percent net revenue retention across the last six quarterly cohorts, calculated on the definition in Appendix B" is evidence.

Definitional hygiene is where credibility is won or lost. Every metric in the memo should carry a consistent, stated definition, because sophisticated readers test exactly this: whether churn is logo or revenue, whether CAC includes salaries or just media spend, whether gross margin absorbs customer success. A memo whose metrics survive definitional cross-examination reads as the product of a company that manages by those numbers rather than one that assembled them for the raise.

Present the trend, not the snapshot. A single strong quarter proves little; six quarters of cohort payback improving from nineteen months to eleven proves a machine is being tuned. Where a number moved the wrong way, show it and explain it, because the reader will find it anyway, and finding it disclosed builds precisely the trust that finding it hidden destroys.

## Risks and Mitigants

Acknowledging risks builds credibility. The best memos pair each material risk with a mitigant or management plan, stated with the same specificity as the opportunity: not "competition is intense" but "two funded competitors are discounting into our mid-market segment; our response is the enterprise-tier migration described in Section 4, where win rates have held at 61 percent." Omission of obvious risks signals inexperience or evasiveness, and the reader cannot tell which, so both are priced in.

Choose the honest three or four rather than the defensive ten. A litany of boilerplate risks reads as legal cover; a short list of the risks management actually loses sleep over, customer concentration, key-person dependency in engineering, a regulatory review with an uncertain date, reads as self-awareness. The purpose of the section is not to disarm every objection but to demonstrate that the people asking for capital see their business as clearly as the people being asked to provide it.

## Before It Goes Out

The final test of a memo is adversarial reading. Have someone unaffiliated with the company, ideally someone who evaluates deals professionally, read it cold and mark every claim they doubted, every number they could not reconcile, and every question it raised without answering. Then fix the document, not the reader. A memo that survives one honest adversarial pass before it circulates will survive the twenty it receives after.`,
  },
  {
    slug: '14-week-growth-round-equity-process-map',
    title: 'The 14-Week Growth-Round Equity Process Map',
    excerpt:
      'How growth-stage equity cycles lengthened, and what founders should do each phase from readiness through close.',
    subtitle:
      'Why the Growth-Stage Equity Cycle Doubled, and How Founders Should Plan for It in H2 2026',
    docCode: 'KP/WP-2026-06-BBR',
    readTime: '18 min read',
    date: 'June 15, 2026',
    coverDate: '2026-06-15',
    icon: 'calendar',
    takeaways: [
      'Fourteen weeks is now the operational base case for institutional growth rounds, not eight.',
      'The four weeks before launch are the highest-leverage period: data room, prospect map, narrative.',
      'Compare term sheets on structure and exit-scenario dilution, not headline valuation alone.',
      'Build a thirty-percent time buffer into runway planning for confirmatory diligence and close.',
    ],
    stats: [
      'Median time-to-close for US growth-stage equity rounds reached 14 weeks in H1 2025, against 8 weeks in 2023 and 7 weeks in 2021 (Source: Cooley GO Quarterly Venture Financing Reports).',
      'Participating preferences appeared in roughly 38 percent of growth-stage rounds in H1 2025, against approximately 22 percent in 2022 (Source: Carta H2 2025 State of Private Markets).',
      'Pro-rata-in-perpetuity provisions appeared in roughly 32 percent of growth rounds in 2024–2025, against an estimated 18 percent in 2021; full-ratchet anti-dilution re-emerged in approximately 7 percent of late growth-stage rounds in 2025 (Source: NVCA Yearbook 2025).',
      'Median growth-equity syndicate size reached 5.2 named co-investors per round in H1 2026, with cross-border deals running 9 or more (Source: Bloomberg H1 2026 ECM data).',
      'Lead follow-on rates range from 38 percent at the bottom quartile to 74 percent at the top quartile, meaning founders should know which quartile each mapped prospect sits in before the first meeting (Source: NVCA Yearbook 2025).',
      'A 4 percent headline valuation premium can correspond to 5 to 7 percentage points of additional founder dilution in a 4x exit when participation, pro-rata, and anti-dilution structure are modeled (Source: Keningford Partners analysis).',
    ],
    content: `Growth-stage equity processes have lengthened. What was often an eight-week median cycle earlier in the decade is now closer to a fourteen-week base case for many institutional rounds. Founders launching a growth raise in 2026 should plan runway for that timeline plus buffer for confirmatory diligence and legal close, not treat a compressed close as the default.

Three forces stretched the cycle. Term sheets carry more structure: participating preferences, broader pro-rata rights, and occasional anti-dilution provisions appear more frequently than in the prior easy-capital window. Syndicates are larger and more diverse, which adds coordination time. Investor diligence has deepened, multi-stage investment committee review, longer cohort analysis, and pre-term-sheet structuring conversations are now routine rather than exceptional.

This guide maps the fourteen-week cycle into phases, clarifies what founders should be doing in each window, and aligns with the readiness framework Keningford Partners uses when advising growth-stage CEOs.

## Weeks −4 to 0: Readiness Before Launch

The four weeks before the first investor meeting are the highest-leverage period in the entire cycle, because everything done here compresses the fourteen weeks that follow and everything skipped here extends them. Three workstreams should run in parallel: building the data room in investor-priority order (cohort economics, monthly P&L reconciled to budget, concentration analysis, preference math under exit scenarios), mapping twenty-five to forty prospects at the partner level, and calibrating the narrative around structural readiness, not growth metrics alone.

Data room sequencing deserves emphasis because most teams build it backwards, starting with corporate housekeeping because those documents are easiest to gather. Investors read in the opposite order: cohort economics and monthly financials answer the first investment-committee question, so they should be complete and internally consistent before anything else is uploaded. A room whose first folders are strong buys patience for the folders that follow; a room that opens with formation documents and placeholder financials signals a company that launched early.

Prospect mapping at the partner level, rather than the firm level, is the second discipline. The relevant unit of analysis is the individual partner: their board load, their check-size history, their lead follow-on record, and whether they have sponsored a company at this stage through their committee in the past year. Lead follow-on rates range from under forty percent at the bottom quartile of firms to nearly three-quarters at the top; founders should know which quartile each mapped prospect sits in before the first meeting, because it is the single best predictor of how the partnership behaves after the wire.

## Weeks 1–3: Outreach and First Meetings

Launch a sequenced outreach list in waves rather than a single broadcast. Prioritize fit over breadth: a first wave of six to ten well-matched partners generates the pattern feedback needed to tune the narrative, while preserving a second and third wave of fresh prospects for the improved version. A process that contacts all forty prospects in week one has spent its entire audience on the rough draft.

Use early meetings to test narrative clarity and identify diligence questions that will recur. Log every question asked in every meeting; questions that appear once are noise, and questions that appear three times are the diligence agenda telegraphing itself. Update materials based on pattern feedback rather than one-off objections, because rewriting the deck after each meeting reads as uncertainty, while a considered revision between waves reads as responsiveness.

Discipline about signal quality matters throughout this window. Polite interest is not progress: the meaningful positive signals are partner-level questions about structure and use of proceeds, requests for cohort data rather than the deck, and second meetings scheduled with additional partners in the room. Founders who track those signals honestly can tell by week three whether the narrative is landing or whether the second wave should wait for a recalibration.

## Weeks 4–8: Deep Diligence and Competitive Tension

Serious investors move into detailed diligence, and the process character changes from persuasion to verification. Maintain a controlled Q&A process: one intake channel, a named internal owner, a forty-eight-hour response standard, and a living FAQ so every investor receives the same answer in the same words. Parallel conversations answered inconsistently are how careless companies manufacture diligence issues out of nothing.

Keep the data room current as the quarter progresses, because a room whose financials go stale mid-process reads as a company losing control of its numbers at exactly the moment it is asking to be underwritten on them. Refresh monthly reporting on a fixed calendar day, date-stamp every update, and flag material changes proactively rather than letting an analyst discover them.

Run parallel conversations so no single counterparty controls timing, and be honest about sequencing intent without staging false tension; sophisticated investors detect manufactured competition quickly and price it as a character signal. Management should be able to speak to unit economics and capital priorities without relying solely on slides, because weeks four through eight are when partners engineer unscripted exposure, the working session, the dinner, the call with the skeptical colleague, precisely to see whether the numbers live in the operators or in the deck.

## Weeks 9–11: Term Sheets and Structure

Compare offers on more than headline valuation. Model participation, pro-rata, and anti-dilution effects on founder outcomes across at least three exit scenarios before choosing a lead, because structure compounds silently: a four percent premium on headline price can correspond to five to seven percentage points of additional founder dilution in a four-times exit once a participating preference and broad pro-rata rights are modeled through the waterfall. The spreadsheet takes an afternoon; signing without it costs real money years later.

Structure has hardened across the market and founders should negotiate accordingly. Participating preferences now appear in a large minority of growth rounds, pro-rata-in-perpetuity provisions have roughly doubled since 2021, and full-ratchet anti-dilution has re-emerged at the margins of late-stage deals. None of these terms is automatically disqualifying, but each one is a price, and the negotiating error is treating the valuation as the deal and the structure as boilerplate.

Reference-check the lead partner with the same rigor they are applying to the company. Call founders from their portfolio, including at least one whose company underperformed, and ask about behavior in the hard quarters: the bridge that did or did not come, the board dynamics after a missed plan, the follow-on decision. Terms govern the downside, but the partner is the daily reality, and this is the last window in which the founder holds full leverage to choose.

## Weeks 12–14: Confirmatory Diligence and Close

Lock exclusivity only when terms and process confidence justify shutting down the alternatives, because exclusivity is the moment leverage transfers to the buyer of the round. Before granting it, confirm that the term sheet is fully negotiated rather than agreed in outline; economics that are vague at signing do not improve in documentation, and the quiet weeks of confirmatory work are where under-negotiated deals erode one clarification at a time.

Complete confirmatory work, documentation, and closing conditions with counsel driving a dated checklist in which every condition has a named owner. Unowned closing conditions are where closings slip, and slippage in this window is expensive because the company has typically stopped fundraising, started planning against the new capital, and begun communicating internally as if the round were done.

Build a thirty-percent time buffer into runway planning for slip risk, and plan the close communications deliberately: employees, existing investors, and key customers should hear the news from the company, in that order, not from the announcement. A close is a beginning as much as an ending, and the first board cycle after the wire sets the operating rhythm for the entire hold.

## Practical Implications

If readiness work is complete at launch, a fourteen-week cycle is often manageable on existing runway. If readiness is incomplete, a bridge sized to finish preparation plus the cycle plus buffer may be necessary, sized to the work it funds, not as a pre-emption of the growth round. The sizing discipline matters: a bridge raised to avoid the readiness work simply moves the same problems into a more expensive conversation six months later.

The arithmetic founders should carry is the honest end-to-end number. Four preparation weeks plus fourteen process weeks plus a thirty percent buffer is roughly six months from decision to funds wired, and the companies that treat that as the planning base case launch calm, negotiate from strength, and close on schedule. Founders six to twelve months from a growth process can start with Keningford's raise readiness diagnostic, then use this map to sequence preparation against a realistic close window.`,
    faq: [
      {
        question: 'How long does a growth round take in 2026?',
        answer:
          'Cooley GO\u2019s Quarterly Venture Financing Reports place the median time-to-close for US growth-stage equity rounds at roughly fourteen weeks in H1 2025, against an eight-week median in 2023. Keningford Partners expects the fourteen-to-eighteen-week range to remain the operational base case through 2026 and 2027, because the structural drivers, deeper diligence, larger syndicates, harder term-sheet structure, are not cyclical.',
      },
      {
        question: 'What should a founder be doing in the weeks before launching a growth-round process?',
        answer:
          'The four weeks before the first investor meeting are the highest-leverage period in the cycle. Three workstreams run in parallel: building the data room to investor-priority order (customer cohort analysis, monthly P&L reconciled to budget, customer concentration, preference math under multiple exit scenarios), mapping twenty-five to forty prospects at the partner level, and calibrating the narrative around structural readiness rather than growth metrics alone.',
      },
      {
        question: 'How have growth-stage term sheets changed in recent years?',
        answer:
          'Carta\u2019s State of Private Markets data shows participating preferences appearing in roughly 38 percent of growth-stage rounds in H1 2025, against approximately 22 percent in 2022. NVCA Yearbook data shows pro-rata-in-perpetuity provisions in roughly 32 percent of growth rounds in 2024–2025, against an estimated 18 percent in 2021, with full-ratchet anti-dilution re-emerging in a small share of late growth-stage rounds in 2025.',
      },
      {
        question: 'Should a founder take a bridge round before launching a growth round?',
        answer:
          'We advise founders to size a bridge to the work it is funding, structural readiness preparation, not pre-emption of the growth round itself. If readiness work is complete at launch, a fourteen-week cycle is typically manageable on existing runway. If readiness work is incomplete, a bridge may be necessary, sized to complete the work plus the cycle plus a buffer of roughly thirty percent.',
      },
      {
        question: 'Who is Keningford Partners?',
        answer:
          'Keningford Partners is a New York-based, principal-led capital advisory and M&A firm advising companies from Series A through the pre-IPO stage, alongside institutional investors, on equity, debt, and strategic transactions. Every mandate is led directly by senior bankers from origination through close.',
      },
      {
        question: 'Where can a founder reach Keningford Partners?',
        answer:
          'Founders six to twelve months from launching a growth-round process can start with Keningford\u2019s raise readiness diagnostic at keningfordpartners.com/raise-readiness, request a review through our contact page, or write to info@keningfordpartners.com.',
      },
    ],
  },
];

export function getInvestorGuideBySlug(slug: string): InvestorGuide | undefined {
  return investorGuides.find((guide) => guide.slug === slug);
}
